TITLE = ["iPhone X ", "Samsung Galaxy S9 ", "Vivo X21 ", "Nokia 8 ", "Google Pixel 2 "];

IMAGE = ["iphonex.jpg", "samsungs9.jpg", "vivox21.jpg", "nokia8.jpg", "pixel2.jpg"];

DESC = ["Indeed, Apple CEO Tim Cook called the new iPhone X 'the biggest leap forward since the original iPhone', and it's easy to see why. The OLED display - an iPhone first - is called the Super Retina Display and measures 5.8 inches, with a resolution of 2,436 x 1,125 pixels. It features Dolby Vision and HDR10 for stunning high-contrast video playback, as well as TrueTone dynamic white-balance adjustment, a feature of the 10.5-inch iPad Pro and the new iPhone 8 models. The screen takes up the whole screen and there's no home button - you unlock your phone with your face. Also, it's water- and dust-resistant, and capable of charging wirelessly.", "Samsung's new Galaxy S9 and S9+ are definitely iterative updates over last year's dramatically redesigned Galaxy S8 series, but that's not a problem. Instead of going back to the drawing board altogether, Samsung focused on fixing a lot of the issues while making drastic improvements to the camera experience and retaining everything that made the last generation so great.", "Vivo X21 smartphone was launched in March 2018. The phone comes with a 6.28-inch touchscreen display with a resolution of 1080 pixels by 2280 pixels. The Vivo X21 is powered by octa-core Qualcomm Snapdragon 660 processor and it comes with 6GB of RAM. The phone packs 64GB of internal storage. As far as the cameras are concerned, the Vivo X21 packs a 12-megapixel primary camera on the rear and a 12-megapixel front shooter for selfies.", "Nokia 8 smartphone was launched in August 2017. The phone comes with a 5.30-inch touchscreen display with a resolution of 1440 pixels by 2560 pixels at a PPI of 554 pixels per inch. The Nokia 8 is powered by 1.8GHz octa-core Qualcomm Snapdragon 835 processor and it comes with 4GB of RAM. The phone packs 64GB of internal storage that can be expanded up to 256GB via a microSD card. As far as the cameras are concerned, the Nokia 8 packs a 13-megapixel primary camera on the rear and a 13-megapixel front shooter for selfies. The Nokia 8 runs Android 7.1.1 and is powered by a 3090mAh non removable battery. It measures 151.50 x 73.70 x 7.90 (height x width x thickness) and weigh 160.00 grams.", "The relentless march of phone releases presses on and we're fresh from the launches of flagships from Samsung, with the Galaxy S9, and Nokia's 8 Sirocco handset. This, of course, puts older handsets - even if they're older by mere months - on the back foot, such as Google's Pixel 2. However, Google has just revealed it is ending OS support for some of its even older models this year, namely the Nexus 5X and Nexus 6P, meaning there is a very valid reason to trade up. With this in mind, especially if you're a fan of Google's range, you may be torn about upgrading to the Pixel 2."];

REVS1 = ["5", "Best phone I have ever bought! Works as intended!", "1", "Terrible phone, came in the mail snapped in half.", "3", "Reliable and has a nice feel! It's okay!", "4", "Extremely convenient, fast, reliable, and has a sleek look. I would recommend this phone to anyone!"];

REVS2 = ["2", "This phone is disgustingly ugly. Why would anyone buy a Samsung?!", "1", "Lost for words", "4", "Great phone! It has great colors and features!", "5", "WOOOOO!"];

REVS3 = ["1", "Stick with the iPhoneX, it's way better." , "5", "IT'S SO MUCH BETTER THAN THE IPHONE X!!!", "4", "dropped it after I walked out of the store and not a scratch!", "2", "Why does it look just like the iphone X?"];

REVS4 = ["4", "Great Look", "3", "Nice curved structure and works well.", "1", "Ugly phone.", "5", "I approve greatly."];

REVS5 = ["5", "Amazing phone! Google really outdid themselves.", "2", "What is this?", "1", "I HATE EVERYTHING ABOUT THIS PHONE!!!", "4", "Nice, I like it."];

PRICE = ["$1,000.00", "$699.99", "$500.00", "$400.00", "$600.00"];